.gitignore, README.md, build.js, components/gbbo-footer.js, components/gbbo-header.js, components/gbbo-welcome-card.js, index.html, js/main.js, package.json, postcss.config.js, src/input.css, tailwind.config.js, vite.config.js
=> Initial commit (thanks Cursor)

components/gbbo-header.js, components/gbbo-welcome-card.js, index.html
=> Little initial UI tweaks

components/gbbo-contestants-data.js, components/gbbo-contestants-modal.js, index.html
=> Add bio modal to contestants

components/gbbo-header.js, components/gbbo-rules-card.js, js/main.js, rules.html, vite.config.js
=> Add rules pages

components/gbbo-rules-card.js, components/gbbo-welcome-card.js
| Before | After |
|--------|--------|
| <img width="1141" height="512" alt="Screenshot 2025-08-30 at 7 42 17 PM" src="https://github.com/user-attachments/assets/e57a5d87-f88c-452f-bf41-3131fb75e4e5" /> | <img width="1235" height="606" alt="Screenshot 2025-08-30 at 7 42 23 PM" src="https://github.com/user-attachments/assets/0a5621c0-7250-42f6-b6c1-c44a0141a7b9" /> |
=> Fix card  widths for responsiveness

components/gbbo-next-week-card.js, index.html, js/main.js
=> Initial weekly promo commit

components/gbbo-contestants-data.js, components/gbbo-contestants-modal.js, components/gbbo-footer.js, components/gbbo-header.js, components/gbbo-next-week-card.js, components/gbbo-rules-card.js, components/gbbo-standings.js, components/gbbo-welcome-card.js, index.html, src/input.css, tailwind.config.js
Vibe coding whimsy. Definitely needs some updates.
=> Color updates

components/gbbo-next-week-card.js
Need to adjust width so it doesn't pop around like crazy between 10s and 9s and 0s to 59s
=> Add countdown timer to homepage

components/foundations/primary-button.js, components/gbbo-header.js, components/gbbo-next-week-card.js
=> Add primary-button component

components/gbbo-header.js, components/gbbo-rules-card.js, js/main.js
=> Sep 1 nit picks

components/gbbo-footer.js, components/gbbo-standings.js, vite.config.js
=> Default to last years standings. Fix assets build.

components/gbbo-header.js
=> Update vote button text

components/gbbo-next-week-card.js
=> Placeholder for Next Week card

components/gbbo-footer.js, components/gbbo-mobile-banner.js, vote.html
=> Add vote banner bc Ryan keeps asking for it

components/foundations/card.js, components/gbbo-header.js, components/gbbo-mobile-banner.js, components/gbbo-next-week-card.js, components/gbbo-rules-card.js, components/gbbo-welcome-card.js, contestants.html, index.html, rules.html, standings.html, vote.html
=> Full screen container updates

components/gbbo-contestants-card.js, components/gbbo-rules-card.js, contestants.html, index.html, rules.html, standings.html, vote.html
=> Revert container for larger screens

components/gbbo-join.js, join.html, js/main.js, js/utils/join.js, vite.config.js
=> Add join page

components/gbbo-banner.js, js/main.js, vote.html
=> Add initial Join League banner on Vote page

components/gbbo-next-week-card.js
=> Tweaking out

components/gbbo-finals.js, finals.html, js/airtable-service.js, js/main.js, js/utils/nominations.js, tailwind.config.js, vite.config.js
=> Add /finals page

2024.html
=> Update to Current Standings. Save 2024 data.

components/contestants/gbbo-contestants-card.js, components/contestants/gbbo-contestants-data.js
=> Update results from CAKE WEEK

components/home/gbbo-standings.js, js/utils/bakers.js, js/utils/participants.js
=> Alphabetize lists

components/vote/gbbo-vote.js, js/utils/nominations.js
=> Preload nominations in the vote form if one already exists
